/**
 * Turns a live n8n workflow into a committable artefact.
 *
 * Two jobs, both of which must be deterministic — `make export` on an unchanged
 * workflow has to produce a byte-identical file, otherwise every export shows up
 * as a spurious diff and the round-trip test in tooling/tests is meaningless.
 *
 *   1. Strip instance-local state (ids, versionIds, webhookIds, pinned data).
 *   2. Rewrite Config node values to the placeholders declared in manifest.json,
 *      so a maintainer's real email address can never reach the repo.
 *
 * See docs/adr/0004-config-node-over-env-vars.md for why configuration lives in
 * a Config node rather than $env.
 */

/** Keys that describe *this* n8n instance and mean nothing in another one. */
const INSTANCE_LOCAL_WORKFLOW_KEYS = [
  'id',
  'versionId',
  'activeVersionId',
  'active',
  'isArchived',
  'createdAt',
  'updatedAt',
  'triggerCount',
  'shared',
  'scopes',
  'canExecute',
  'homeProject',
  'sharedWithProjects',
  'parentFolderId',
  'activeVersion',
  'pinData',
  // Polling cursors (`lastTimeChecked`) — replaying another instance's cursor
  // would make a fresh instance skip mail it has never seen.
  'staticData',
  'usedCredentials',
  // Version bookkeeping from the instance's own history.
  'versionCounter',
  'versionMetadata',
  // `shared` embeds the owning project, whose name contains the owner's email
  // address. This is the field most likely to leak PII on a naive export.
  'shared'
];

/** Node-level keys that are regenerated by n8n on import. */
const INSTANCE_LOCAL_NODE_KEYS = ['webhookId', 'credentials'];

/** Order the top-level keys so exports are stable regardless of API field order. */
const WORKFLOW_KEY_ORDER = ['name', 'nodes', 'connections', 'settings', 'meta', 'tags'];

/**
 * Recursively sort object keys. JSON.stringify preserves insertion order, so
 * without this the n8n API returning fields in a different order would produce a
 * different file for an identical workflow.
 */
function sortDeep(value) {
  if (Array.isArray(value)) return value.map(sortDeep);
  if (value === null || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.keys(value)
      .sort()
      .map((key) => [key, sortDeep(value[key])])
  );
}

/** Reorder top-level keys into WORKFLOW_KEY_ORDER, then anything else alphabetically. */
function orderWorkflowKeys(workflow) {
  const remaining = Object.keys(workflow)
    .filter((key) => !WORKFLOW_KEY_ORDER.includes(key))
    .sort();
  const ordered = {};
  for (const key of [...WORKFLOW_KEY_ORDER, ...remaining]) {
    if (key in workflow) ordered[key] = workflow[key];
  }
  return ordered;
}

/**
 * Reduce a credential reference to its name.
 *
 * n8n stores `{ id, name }`. The id points at a row in *this* instance's
 * database, so keeping it means a fresh instance tries to bind to a credential
 * that does not exist and the node silently arrives unconfigured. Keeping only
 * the name makes the name a public contract: create a credential called
 * "Gmail account" and import wires it up automatically.
 */
function sanitizeCredentials(credentials) {
  if (!credentials || typeof credentials !== 'object') return undefined;
  const out = {};
  for (const [type, ref] of Object.entries(credentials)) {
    if (!ref) continue;
    const name = typeof ref === 'string' ? ref : ref.name;
    if (name) out[type] = { name };
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

/**
 * Overwrite a Config node's assignment values with their declared placeholders.
 *
 * The live instance holds real values; the repo must only ever hold placeholders.
 * Fields present in the node but absent from the manifest are left untouched and
 * reported, so a newly added config field fails validation rather than leaking.
 */
function applyConfigPlaceholders(node, placeholders, warnings) {
  const assignments = node.parameters?.assignments?.assignments;
  if (!Array.isArray(assignments)) {
    warnings.push(`Config node "${node.name}" has no assignments to sanitise`);
    return node;
  }

  const seen = new Set();
  const sanitizedAssignments = assignments.map((assignment) => {
    if (!Object.prototype.hasOwnProperty.call(placeholders, assignment.name)) {
      warnings.push(
        `Config node "${node.name}" field "${assignment.name}" has no placeholder in manifest.json`
      );
      return assignment;
    }
    seen.add(assignment.name);
    return { ...assignment, value: placeholders[assignment.name] };
  });

  for (const declared of Object.keys(placeholders)) {
    if (!seen.has(declared)) {
      warnings.push(
        `manifest.json declares "${node.name}.${declared}" but the node has no such field`
      );
    }
  }

  return {
    ...node,
    parameters: {
      ...node.parameters,
      assignments: { ...node.parameters.assignments, assignments: sanitizedAssignments }
    }
  };
}

/**
 * @param {object} workflow  Raw workflow object from the n8n API.
 * @param {object} [manifest] Parsed manifest.json; supplies `configNodes`.
 * @returns {{ workflow: object, warnings: string[] }}
 */
export function sanitizeWorkflow(workflow, manifest = {}) {
  const warnings = [];
  const configNodes = manifest.configNodes ?? {};

  const nodes = (workflow.nodes ?? []).map((rawNode) => {
    let node = { ...rawNode };

    for (const key of INSTANCE_LOCAL_NODE_KEYS) delete node[key];

    const credentials = sanitizeCredentials(rawNode.credentials);
    if (credentials) node.credentials = credentials;

    if (Object.prototype.hasOwnProperty.call(configNodes, node.name)) {
      node = applyConfigPlaceholders(node, configNodes[node.name], warnings);
    }

    return node;
  });

  for (const declaredNode of Object.keys(configNodes)) {
    if (!nodes.some((node) => node.name === declaredNode)) {
      warnings.push(
        `manifest.json declares config node "${declaredNode}" which is not in the workflow`
      );
    }
  }

  const cleaned = { ...workflow, nodes };
  for (const key of INSTANCE_LOCAL_WORKFLOW_KEYS) delete cleaned[key];

  // `meta` carries instanceId, which identifies the machine that exported it.
  if (cleaned.meta && typeof cleaned.meta === 'object') {
    const { instanceId, ...meta } = cleaned.meta;
    if (Object.keys(meta).length > 0) cleaned.meta = meta;
    else delete cleaned.meta;
  }

  // Nodes keep their declaration order (it mirrors the canvas); everything
  // nested inside them is sorted so field ordering cannot churn the diff.
  const { nodes: _unsortedNodes, ...withoutNodes } = cleaned;
  const stable = orderWorkflowKeys({
    ...sortDeep(withoutNodes),
    nodes: nodes.map(sortDeep)
  });

  return { workflow: stable, warnings };
}

/** Canonical on-disk form: 2-space JSON with a trailing newline, LF endings. */
export function serializeWorkflow(workflow) {
  return `${JSON.stringify(workflow, null, 2)}\n`;
}

/** Convenience: sanitize + serialize in one step. */
export function toRepoFormat(workflow, manifest = {}) {
  const { workflow: sanitized, warnings } = sanitizeWorkflow(workflow, manifest);
  return { content: serializeWorkflow(sanitized), warnings };
}
